{{/*
Expand the name of the chart.
*/}}
{{- define "vulkan.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "vulkan.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "vulkan.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common resource labels (general metadata, not for selector match unless explicitly added)
This helper should NOT include app.kubernetes.io/name, instance, or component as those are for identity/matching.
*/}}
{{- define "vulkan.commonResourceLabels" -}}
helm.sh/chart: {{ include "vulkan.chart" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Common labels for all resources in the chart.
Optionally accepts a 'component' parameter to add app.kubernetes.io/component label.
Usage: {{ include "vulkan.labels" . }} or {{ include "vulkan.labels" (dict "context" . "component" "controller") }}
*/}}
{{- define "vulkan.labels" -}}
{{- $context := .context | default . -}}
{{- $component := .component | default "" -}}
helm.sh/chart: {{ include "vulkan.chart" $context }}
{{- if $context.Chart.AppVersion }}
app.kubernetes.io/version: {{ $context.Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ $context.Release.Service }}
app.kubernetes.io/name: {{ include "vulkan.name" $context }}
app.kubernetes.io/instance: {{ $context.Release.Name }}
{{- if $component }}
app.kubernetes.io/component: {{ $component }}
{{- end }}
{{- end }}



{{/*
Selector labels for a component.
Usage: {{ include "vulkan.componentSelectorLabels" (dict "context" . "component" "ui") }}
*/}}
{{- define "vulkan.componentSelectorLabels" -}}
{{- $context := .context -}} 
{{- $component := .component -}}
app.kubernetes.io/name: {{ include "vulkan.name" $context }}
app.kubernetes.io/instance: {{ $context.Release.Name }}
app.kubernetes.io/component: {{ $component }}
{{- end }}


{{/*
Create the name of the service account to use
*/}}
{{- define "vulkan.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "vulkan.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}


{{/* define ui deployment name */}}
{{- define "vulkan.uiDeploymentName" -}}
{{- printf "%s-ui-deployment" (include "vulkan.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/* define ui service name */}}
{{- define "vulkan.uiServiceName" -}}
{{- printf "%s-ui-service" (include "vulkan.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/* define api deployment name */}}
{{- define "vulkan.apiDeploymentName" -}}
{{- printf "%s-api" (include "vulkan.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/* define api service name */}}
{{- define "vulkan.apiServiceName" -}}
{{- printf "%s-api" (include "vulkan.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/* define ui ingress name */}}
{{- define "vulkan.uiIngressName" -}}
{{- printf "%s-ui-ingress" (include "vulkan.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/* define api ingress name */}}
{{- define "vulkan.apiIngressName" -}}
{{- printf "%s-api-ingress" (include "vulkan.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create the name of the ServiceAccount for Tekton PipelineRuns.
This name is referenced by the ApplicationReconciler.
*/}}
{{- define "vulkan.tektonServiceAccountName" -}}
{{- default "tekton-sa" .Values.tekton.serviceAccountName }}
{{- end }}


# helpers for operator charts (autogenerated)

{{- define "chart.name" -}}
{{- if .Chart }}
  {{- if .Chart.Name }}
    {{- .Chart.Name | trunc 63 | trimSuffix "-" }}
  {{- else if .Values.nameOverride }}
    {{ .Values.nameOverride | trunc 63 | trimSuffix "-" }}
  {{- else }}
    operator
  {{- end }}
{{- else }}
  operator
{{- end }}
{{- end }}


{{- define "chart.labels" -}}
{{- if .Chart.AppVersion -}}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
{{- if .Chart.Version }}
helm.sh/chart: {{ .Chart.Version | quote }}
{{- end }}
app.kubernetes.io/name: {{ include "chart.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}


{{- define "chart.selectorLabels" -}}
app.kubernetes.io/name: {{ include "chart.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- define "chart.hasMutatingWebhooks" -}}
{{- $hasMutating := false }}
{{- range . }}
  {{- if eq .type "mutating" }}
    $hasMutating = true }}{{- end }}
{{- end }}
{{ $hasMutating }}}}{{- end }}


{{- define "chart.hasValidatingWebhooks" -}}
{{- $hasValidating := false }}
{{- range . }}
  {{- if eq .type "validating" }}
    $hasValidating = true }}{{- end }}
{{- end }}
{{ $hasValidating }}}}{{- end }}
