{{- if .Values.dex.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts: [ "dex.{{ .Values.global.domain }}" ]
      secretName: dex-tls                           # cert-manager will fill
  rules:
    - host: dex.{{ .Values.global.domain }}
      http:
        paths:
          - path: /dex
            pathType: Prefix
            backend:
              service:
                name: {{ include "dex.fullname" . }}   # sub-chart Service
                port:
                  number: 5556
{{- end }}
