{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vulkan.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vulkan.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
# Add cluster-admin permissions to service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vulkan.serviceAccountName" . }}-admin
  labels:
    {{- include "vulkan.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "vulkan.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
