{{- /*
Secret to hold vulkan api secrets:
  - Database URL With embedded password

*/ -}}
apiVersion: v1
kind: Secret
metadata:
  name: vulkan-api-secrets
  labels:
    {{- include "vulkan.commonResourceLabels" . | nindent 4 }}
type: Opaque
stringData:
  databaseUrl: {{ .Values.secrets.databaseUrl | quote }}