apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulkan.uiDeploymentName" . }}
  labels:
    {{- include "vulkan.commonResourceLabels" . | nindent 4 }}
    {{- include "vulkan.componentSelectorLabels" (dict "context" . "component" "ui") | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicas | default 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
     {{- include "vulkan.componentSelectorLabels" (dict "context" . "component" "ui") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vulkan.componentSelectorLabels" (dict "context" . "component" "ui") | nindent 8 }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 80
          env:
            {{- toYaml .Values.ui.env | nindent 12 }}  # This renders the entire list from values.yaml
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}