apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulkan.uiServiceName" . }}
  labels:
    {{- include "vulkan.commonResourceLabels" . | nindent 4 }}
    {{- include "vulkan.componentSelectorLabels" (dict "context" . "component" "ui") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    # This selector MUST match the labels on the actual pods managed by the UI Deployment.
    # We use the same helper as the Deployment's matchLabels.
    {{- include "vulkan.componentSelectorLabels" (dict "context" . "component" "ui") | nindent 4 }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http # This matches the 'name' of the port in the container spec