apiVersion: v2
name: vulkan
description: Self-hostable PaaS control-plane
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
 # Install cert-manager first with CRDs
  - name: cert-manager
    version: v1.14.4 
    repository: https://charts.jetstack.io
    alias: certmanager # This is the key we use in values.yaml
    condition: certmanager.enabled # Enable/disable via values.yaml
  - name: tekton-pipeline
    version: 1.1.0
    repository: https://cdfoundation.github.io/tekton-helm-chart
    alias: tekton
  - name: nats
    version: 1.3.0
    repository: https://nats-io.github.io/k8s/helm/charts
    alias: nats
  - name: crossplane
    version: 1.17.0
    repository: https://charts.crossplane.io/stable
  - name: argo-cd
    version: 5.53.6
    repository: https://argoproj.github.io/argo-helm
    alias: argocd
  - name: dex
    version: 0.17.0          
    repository: https://charts.dexidp.io
    alias: dex
    condition: dex.enabled
  - name: ingress-nginx
    alias: nginx
    version: 4.10.0
    repository: https://kubernetes.github.io/ingress-nginx