# templates/tekton/tekton-serviceaccount-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vulkan.tektonServiceAccountName" . }}
  labels:
    {{- include "vulkan.labels" (dict "context" . "component" "tekton-pipeline") | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vulkan.tektonServiceAccountName" . }}-role
  labels:
    {{- include "vulkan.labels" (dict "context" . "component" "tekton-pipeline") | nindent 4 }}
rules:
  # Permissions for Tekton internal operations (creating TaskRuns/Pods)
  - apiGroups: ["tekton.dev"]
    resources: ["tasks", "pipelines"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Permissions for the tasks to interact with Kubernetes resources
  - apiGroups: [""] # Core API group
    resources: ["pods", "pods/log", "pods/status"] # Include /log and /status for better debugging
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"] # For mounting credentials/configs
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # For volumeClaimTemplate
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"] # To get its own service account information
  # Permissions specifically for the 'update-gitops-repo-task'
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""] # Core API group for Services (if update-gitops-repo-task might update services too)
    resources: ["services"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vulkan.tektonServiceAccountName" . }}-rolebinding
  labels:
    {{- include "vulkan.labels" (dict "context" . "component" "tekton-pipeline") | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vulkan.tektonServiceAccountName" . }}
    namespace: {{ .Release.Namespace }} # Use current release namespace
roleRef:
  kind: Role
  name: {{ include "vulkan.tektonServiceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io