apiVersion: v1
kind: Secret
metadata:
  name: vulkan-docker-config-secret
  labels:
    {{- include "vulkan.commonResourceLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.dockerConfigJson | b64enc | quote }}