apiVersion: v1
kind: Secret
metadata:
  name: vulkan-git-credentials-secret
  labels:
    {{- include "vulkan.commonResourceLabels" . | nindent 4 }}
type: Opaque
stringData:
  .git-credentials: |
    {{ .Values.secrets.gitCredentials | nindent 12 }}