---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.platform.io
  resources:
  - applications
  - orgs
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.platform.io
  resources:
  - applications/finalizers
  - orgs/finalizers
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - platform.platform.io
  resources:
  - applications/status
  - orgs/status
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tekton.dev
  resources:
  - clustertasks
  - pipelineruns
  - pipelines
  - taskruns
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
