---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - platform.platform.io
  resources:
  - applications
  - orgs
  - projectclusterbindings
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.platform.io
  resources:
  - applications/finalizers
  - orgs/finalizers
  - projectclusterbindings/finalizers
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - platform.platform.io
  resources:
  - applications/status
  - orgs/status
  - projectclusterbindings/status
  - projects/status
  verbs:
  - get
  - patch
  - update
