{{- if .Values.rbac.enable }}
# This rule is not used by the project operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to platform.platform.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: org-viewer-role
rules:
- apiGroups:
  - platform.platform.io
  resources:
  - orgs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.platform.io
  resources:
  - orgs/status
  verbs:
  - get
{{- end -}}
