{{- if .Values.rbac.enable }}
# This rule is not used by the project operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over platform.platform.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: org-admin-role
rules:
- apiGroups:
  - platform.platform.io
  resources:
  - orgs
  verbs:
  - '*'
- apiGroups:
  - platform.platform.io
  resources:
  - orgs/status
  verbs:
  - get
{{- end -}}
