apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulkan.apiDeploymentName" . }}
  labels:
    {{- include "vulkan.commonResourceLabels" . | nindent 4 }}
    {{- include "vulkan.componentSelectorLabels" (dict "context" . "component" "api-server") | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas | default 2 }}
  selector:
    matchLabels:
      {{- include "vulkan.componentSelectorLabels" (dict "context" . "component" "api-server") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vulkan.componentSelectorLabels" (dict "context" . "component" "api-server") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "vulkan.serviceAccountName" . }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          env:
            - name: OIDC_JWKS_URL
              value: "{{ include "vulkan.dexInternalUrl" . }}/keys"
            - name: OIDC_ISSUER
              value: "{{ include "vulkan.dexExternalUrl" . }}"
            - name: DEX_URL
              value: "{{ include "vulkan.dexInternalUrl" . }}"
            - name: OIDC_CLIENT_ID
              value: "vulkan-api"
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vulkan-dex-auth
                  key: apiClientSecret
            - name: K8S_IN_CLUSTER
              value: "true"
            - name: VULKAN_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vulkan-api-secrets
                  key: databaseUrl
            - name: OPA_URL
              value: "http://127.0.0.1:8181"
            - name: OPA_POLICY_PATH
              value: "/data/api/authz/allow"
            - name: NATS_URL
              value: "nats://nats:4222"
          imagePullPolicy: {{ .Values.api.image.pullPolicy | default "IfNotPresent" }} # Removed | quote
          ports:
            - name: http
              containerPort: 8080
        - name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:8181"
            - "--config-file=/config/config.yaml"
          volumeMounts:
            - name: opa-config
              mountPath: /config
      volumes:
        - name: opa-config
          configMap:
            name: opa-config