{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vulkan.apiIngressName" . }}
  annotations:
    # Remove the deprecated kubernetes.io/ingress.class annotation.
    # The ingressClassName field in spec is the correct way for v1 Ingress.
{{- with .Values.api.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className | default "nginx" }}
  tls:
    - hosts:
        -  {{ .Values.api.ingress.host }}
      secretName: {{ .Values.api.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vulkan.apiServiceName" . }}
                port:
                  number: 8080
{{- end }}
