apiVersion: v2
name: vulkan
description: Self-hostable PaaS control-plane
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: nats
    version: 1.3.0
    repository: https://nats-io.github.io/k8s/helm/charts
    alias: nats
  - name: crossplane
    version: 1.17.0
    repository: https://charts.crossplane.io/stable
  - name: tekton-pipeline
    version: 0.54.0
    repository: https://tekton-charts.storage.googleapis.com
    alias: tekton
  - name: argo-cd
    version: 5.53.6
    repository: https://argoproj.github.io/argo-helm
    alias: argocd