apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-cert
spec:
  secretName: dex-tls
  dnsNames:
    - dex.{{ .Values.global.domain }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
