{{- $fullName := include "vulkan.fullname" . -}}
{{- $uiName   := printf "%s-ui" $fullName -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $uiName }}
  labels:
    {{- include "vulkan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ $uiName }}
    app.kubernetes.io/part-of: {{ $fullName }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.ui.replicas | default 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $uiName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $uiName }}
        {{- include "vulkan.labels" . | nindent 8 }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 3000
          env:
            # Tells the SPA where to reach the internal API Service
            - name: VULKAN_API_BASE
              value: {{ .Values.ui.apiBase | default "http://vulkan-api.vulkan.svc.cluster.local:8080" | quote }}
            - name: VULKAN_OIDC_AUTH_URL
              value: "https://dex.{{ .Values.global.domain }}/dex/auth"
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}