apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulkan.apiDeploymentName" . }}
  labels:
    {{- include "vulkan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "vulkan.apiDeploymentName" . }}
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: {{ include "vulkan.fullname" . }}
spec:
  replicas: {{ .Values.api.replicas | default 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vulkan.apiDeploymentName" . }}
      
  template:
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          env:
            - name: OPA_URL
              value: {{ .Values.api.env.OPA_URL | quote }}
            - name: OPA_POLICY_PATH
              value: {{ .Values.api.env.OPA_POLICY_PATH  | quote }}
            - name: NATS_URL
              value: {{ .Values.api.env.NATS_URL | quote }}
            - name: OIDCJWKSURL
              value: "https://dex.{{ .Values.global.domain }}/dex/keys"
            - name: K8S_IN_CLUSTER
              value: {{ .Values.api.env.K8S_IN_CLUSTER | quote }}
            - name: DATABASE_URL
              value: {{ .Values.api.env.DATABASE_URL | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" | quote }}

          ports:
            - containerPort: 8080
        - name: opa
          image: openpolicyagent/opa:0.60.0-rootless
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:8181"
            - "--ignore=.*" # don't watch non-policy files
            - "/policies"
          volumeMounts:
            - name: opa-bundle
              mountPath: /policies
      volumes:
        - name: opa-bundle
          configMap:
            name: opa-policy-bundle
