name: Build OPA Bundle

on:
  push:
    branches:
      - main
    paths:
      - "policies/**"
      - ".github/workflows/opa-build.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "policies/**"
      - ".github/workflows/opa-build.yaml"

permissions:
  contents: write

jobs:
  build-bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest OPA version
        id: opa-version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/open-policy-agent/opa/releases/latest | jq -r '.tag_name')
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "Latest OPA version: $LATEST_VERSION"

      - name: Install OPA
        run: |
          OPA_VERSION=${{ steps.opa-version.outputs.version }}
          curl -L -o opa https://openpolicyagent.org/downloads/${OPA_VERSION}/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Verify OPA installation
        run: opa version

      - name: Validate policies
        run: |
          opa fmt --diff policies/
          opa test policies/

      - name: Create bundle structure
        run: |
          mkdir -p bundle/api/authz
          cp -r policies/* bundle/api/authz/

      - name: Create manifest
        run: |
          cat > bundle/.manifest << EOF
          {
            "revision": "${{ github.sha }}",
            "roots": ["api"],
            "metadata": {
              "branch": "${{ github.ref_name }}",
              "commit": "${{ github.sha }}",
              "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
              "opa_version": "${{ steps.opa-version.outputs.version }}"
            }
          }
          EOF

      - name: Create bundle
        run: |
          cd bundle
          tar -czf ../bundle.tar.gz .

      - name: Upload bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: opa-bundle
          path: bundle.tar.gz

      - name: Commit bundle to releases branch
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Create or switch to releases branch
          git checkout -B releases-opa

          # Add bundle (already in current directory, no copy needed)
          git add bundle.tar.gz
          git commit -m "Update OPA bundle for commit ${{ github.sha }}" || exit 0
          git push origin releases-opa --force
