name: Operator CI

on:
  push:
    branches:
      - main
    paths:
      - "operator/**" # Trigger when any file in the 'operator' directory changes
      - "go.work" # Crucial: Trigger if the shared go.work file changes
      - ".github/workflows/operator-ci.yaml" # Trigger if this workflow file itself changes
  pull_request:
    branches:
      - main
    paths:
      - "operator/**"
      - "go.work"
      - ".github/workflows/operator-ci.yaml"

# Define permissions required for the workflow
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_OPERATOR: ${{ github.repository }}/operator

jobs:
  build-test-publish-operator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"

      - name: Go work sync (for go.mod replace directives)
        # This step is crucial to ensure `go.work` properly resolves module paths
        # before running tests or building locally.
        run: go work sync
        working-directory: .

      - name: Run Operator tests
        run: |
          go mod tidy
          make test
        working-directory: operator

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Operator image
        uses: docker/build-push-action@v5
        with:
          # The context for the operator is its own directory, as specified
          context: ./operator
          file: ./operator/Dockerfile # Path to the Operator's Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_OPERATOR }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_OPERATOR }}:latest
