name: Publish Helm Chart to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "charts/vulkan-charts/**"
      - ".github/workflows/publish-helm-charts.yaml"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.14.0

      - name: Package Helm Chart
        run: |
          HELM_CHART_SOURCE_PATH="charts/vulkan-charts"

          pushd ${HELM_CHART_SOURCE_PATH}
          echo "Updating Helm chart dependencies for ${HELM_CHART_SOURCE_PATH}..."
          helm dependency update
          popd

          CHART_NAME=$(yq e '.name' ${HELM_CHART_SOURCE_PATH}/Chart.yaml)
          CHART_VERSION=$(yq e '.version' ${HELM_CHART_SOURCE_PATH}/Chart.yaml)

          PACKAGE_OUTPUT_DIR="packaged-charts-temp"
          mkdir -p ${PACKAGE_OUTPUT_DIR}

          helm package ${HELM_CHART_SOURCE_PATH} -d ${PACKAGE_OUTPUT_DIR}

          echo "PACKAGED_CHART_FILE=${PACKAGE_OUTPUT_DIR}/${CHART_NAME}-${CHART_VERSION}.tgz" >> $GITHUB_ENV
          echo "PACKAGED_CHART_DIR=${PACKAGE_OUTPUT_DIR}" >> $GITHUB_ENV

      - name: Prepare Chart Repository Directory
        run: |
          # Create the repository root directory
          REPO_ROOT_FOR_PAGES="gh-pages-repository"
          mkdir -p ${REPO_ROOT_FOR_PAGES}

          # Copy the packaged chart directly to the root (no subdirectory)
          cp ${{ env.PACKAGED_CHART_FILE }} ${REPO_ROOT_FOR_PAGES}/

          # Generate index.yaml with the correct base URL
          CHART_REPO_BASE_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

          echo "Generating index.yaml for Helm repository at ${REPO_ROOT_FOR_PAGES}..."
          helm repo index ${REPO_ROOT_FOR_PAGES} --url "${CHART_REPO_BASE_URL}"

          echo "REPO_ROOT_FOR_PAGES=${REPO_ROOT_FOR_PAGES}" >> $GITHUB_ENV

      - name: Publish Helm Chart to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.REPO_ROOT_FOR_PAGES }}
          destination_dir: .
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          enable_jekyll: true
          full_commit_message: "Publish Helm chart ${{ env.PACKAGED_CHART_FILE }}"
